### ISSUE TITLE
A bug on "A)RoadMap 1"

### ISSUE THREAD

**Issue by Charlottecuc** [Tessellate-Imaging/Pytorch_Tutorial#1]
In [38], there might be a typo.
I think "x_t_squeezed = torch.squeeze(x)" here should be changed to "x_t_squeezed = torch.squeeze(x_t)".

**Comment by abhi-kumar** [comment]
Thank you for pointing it out. If you can create a pull request for the same I will merge it with the current master branch.

Regards,
Abhishek

**Comment by Charlottecuc** [comment]
My pleasure. 

Regards,
Charlotte
